name: main_push

on: push
env:
   BASE: "main"
jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout "${{ env.BASE }}" # チェックアウトするブランチを設定
         uses: actions/checkout@v2.3.2
         with:
           ref: "${{ env.BASE }}"

       - name: Use Node.js 18.17.0
         uses: actions/setup-node@v1
         with:
           node-version: '18.17.0'

       - name: Build Site
         run: |
           npm install
           npm run build

       - name: FTP-Deploy-Action
         uses: SamKirkland/FTP-Deploy-Action@2.0.0
         env:
           FTP_SERVER: ${{ secrets.FTP_SERVER }} # デプロイ先のサーバーURL
           FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # デプロイ先のユーザー名
           FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # デプロイ先のパスワード
           port: ${{ secrets.FTP_PORT }} # デプロイ先のポート番号 21 or 22
           LOCAL_DIR: out/ #デプロイする対象のフォルダ
           REMOTE_DIR: ${{ secrets.REMOTE_DIR }} # デプロイ先のディレクトリ
