name: post save wordpress

on:
  repository_dispatch:
    types: [post_save_wordpress]
env:
   BASE: "main"
jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout "${{ env.BASE }}" # チェックアウトするブランチを設定
         uses: actions/checkout@v2.3.2
         with:
           ref: "${{ env.BASE }}"

       - name: Use Node.js 18.17.0
         uses: actions/setup-node@v1
         with:
           node-version: '18.17.0'

       - name: Build Site
         run: |
           npm install
           npm run build
         env:
          NEXT_PUBLIC_WPDOMAIN: ${{secrets.NEXT_PUBLIC_WPDOMAIN}}
          NEXT_PUBLIC_BASIC_ID: ${{secrets.NEXT_PUBLIC_BASIC_ID}}
          NEXT_PUBLIC_BASIC_PASSWORD: ${{secrets.NEXT_PUBLIC_BASIC_PASSWORD}}
          NEXT_PUBLIC_PER_PAGE: ${{secrets.NEXT_PUBLIC_PER_PAGE}}

       - name: FTP-Deploy-Action
         uses: SamKirkland/FTP-Deploy-Action@v2.0.0
         with:
           FTP_SERVER: ${{ secrets.FTP_SERVER }} # デプロイ先のサーバーURL
           FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # デプロイ先のユーザー名
           FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # デプロイ先のパスワード
           port: ${{ secrets.FTP_PORT }} # デプロイ先のポート番号 21 or 22
           LOCAL_DIR: out/ #デプロイする対象のフォルダ
           REMOTE_DIR: ${{ secrets.REMOTE_DIR }} # デプロイ先のディレクトリ
           ARGS: --delete --parallel=20 -x assets/images
